/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SolutionsCommercialRouteImport } from './routes/solutions_.commercial'
import { Route as SolutionsIndustrialRouteImport } from './routes/solutions_.industrial'
import { Route as SolutionsResidentialRouteImport } from './routes/solutions_.residential'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsCommercialRoute = SolutionsCommercialRouteImport.update({
  id: '/solutions_/commercial',
  path: '/solutions/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndustrialRoute = SolutionsIndustrialRouteImport.update({
  id: '/solutions_/industrial',
  path: '/solutions/industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsResidentialRoute = SolutionsResidentialRouteImport.update({
  id: '/solutions_/residential',
  path: '/solutions/residential',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/application': typeof ApplicationRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/schemes': typeof SchemesRoute
  '/solutions': typeof SolutionsRoute
  '/solutions/commercial': typeof SolutionsCommercialRoute
  '/solutions/industrial': typeof SolutionsIndustrialRoute
  '/solutions/residential': typeof SolutionsResidentialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/application': typeof ApplicationRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/schemes': typeof SchemesRoute
  '/solutions': typeof SolutionsRoute
  '/solutions/commercial': typeof SolutionsCommercialRoute
  '/solutions/industrial': typeof SolutionsIndustrialRoute
  '/solutions/residential': typeof SolutionsResidentialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/application': typeof ApplicationRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/employee': typeof EmployeeRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/schemes': typeof SchemesRoute
  '/solutions': typeof SolutionsRoute
  '/solutions_/commercial': typeof SolutionsCommercialRoute
  '/solutions_/industrial': typeof SolutionsIndustrialRoute
  '/solutions_/residential': typeof SolutionsResidentialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/application'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/employee'
    | '/login'
    | '/products'
    | '/projects'
    | '/quote'
    | '/schemes'
    | '/solutions'
    | '/solutions/commercial'
    | '/solutions/industrial'
    | '/solutions/residential'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/application'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/employee'
    | '/login'
    | '/products'
    | '/projects'
    | '/quote'
    | '/schemes'
    | '/solutions'
    | '/solutions/commercial'
    | '/solutions/industrial'
    | '/solutions/residential'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/application'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/employee'
    | '/login'
    | '/products'
    | '/projects'
    | '/quote'
    | '/schemes'
    | '/solutions'
    | '/solutions_/commercial'
    | '/solutions_/industrial'
    | '/solutions_/residential'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplicationRoute: typeof ApplicationRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  EmployeeRoute: typeof EmployeeRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ProjectsRoute: typeof ProjectsRoute
  QuoteRoute: typeof QuoteRoute
  SchemesRoute: typeof SchemesRoute
  SolutionsRoute: typeof SolutionsRoute
  SolutionsCommercialRoute: typeof SolutionsCommercialRoute
  SolutionsIndustrialRoute: typeof SolutionsIndustrialRoute
  SolutionsResidentialRoute: typeof SolutionsResidentialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/commercial': {
      id: '/solutions_/commercial'
      path: '/solutions/commercial'
      fullPath: '/solutions/commercial'
      preLoaderRoute: typeof SolutionsCommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/industrial': {
      id: '/solutions_/industrial'
      path: '/solutions/industrial'
      fullPath: '/solutions/industrial'
      preLoaderRoute: typeof SolutionsIndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions_/residential': {
      id: '/solutions_/residential'
      path: '/solutions/residential'
      fullPath: '/solutions/residential'
      preLoaderRoute: typeof SolutionsResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplicationRoute: ApplicationRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  EmployeeRoute: EmployeeRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ProjectsRoute: ProjectsRoute,
  QuoteRoute: QuoteRoute,
  SchemesRoute: SchemesRoute,
  SolutionsRoute: SolutionsRoute,
  SolutionsCommercialRoute: SolutionsCommercialRoute,
  SolutionsIndustrialRoute: SolutionsIndustrialRoute,
  SolutionsResidentialRoute: SolutionsResidentialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
